---
- hosts: all
  become: yes

  # This playbook is for provisioning the Development VM only. See prod/provision.yml for the Production playbook.

  vars_files:
    - vars/main.yml
    - ../default.config.yml

  pre_tasks:
    - import_tasks: tasks/config.yml
      tags: ['always']

    - import_tasks: tasks/app-toggles.yml
      tags: ['always']

    - import_tasks: tasks/backwards-compatibility.yml
      tags: ['always']

    - include_tasks: "tasks/init-{{ ansible_os_family }}.yml"

    - name: Run configured pre-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ pre_provision_tasks_dir|default(omit) }}"

    - import_tasks: tasks/php.yml

  roles:
    # Essential roles.
    - { role: drupalvm.hostname, when: hostname_configure }
    - { role: drupalvm.vagrant-nfs-fix, when: vagrant_nfs_fix_enabled }
    - { role: iainhouston.firewall, when: firewall_enabled }
    - { role: geerlingguy.git }
    - { role: geerlingguy.postfix }
    - { role: geerlingguy.apache, when: drupalvm_webserver == 'apache', tags: ['webserver'] }
    - { role: geerlingguy.apache-php-fpm, when: drupalvm_webserver == 'apache', tags: ['webserver'] }
    - { role: geerlingguy.php-versions, when: php_version != '', tags: ['php', 'xdebug', 'database'] }
    - { role: geerlingguy.php, tags: ['php'] }
    - { role: geerlingguy.php-pecl, tags: ['php'] }
    - { role: geerlingguy.composer }
    - { role: iainhouston.mysql, when: drupal_db_backend == 'mysql', tags: ['database'] }
    - { role: geerlingguy.php-mysql, when: drupal_db_backend == 'mysql', tags: ['php', 'database'] }

    # Conditionally-installed roles.
    - { role: geerlingguy.drupal-console, when: 'drupal_major_version > 7 and "drupalconsole" in installed_extras' }
    - { role: geerlingguy.drush, when: '"drush" in installed_extras' }
    - { role: geerlingguy.memcached, when: '"memcached" in installed_extras' }
    - { role: geerlingguy.php-memcached, when: '"memcached" in installed_extras', tags: ['php'] }
    - { role: iainhouston.php-xdebug, when: '"xdebug" in installed_extras', tags: ['php'] }

    - role: geerlingguy.php-xhprof
      workspace: "/root/php{{ php_version }}"
      when: '"xhprof" in installed_extras'
      tags: ['php']

    - role: thom8.php-upload-progress
      workspace: "/root/php{{ php_version }}"
      when: '"upload-progress" in installed_extras'
      tags: ['php']

    - { role: iainhouston.adminer, when: '"adminer" in installed_extras', tags: ['database'] }
    - { role: geerlingguy.daemonize, when: '"mailhog" in installed_extras' }
    - { role: iainhouston.mailhog, when: '"mailhog" in installed_extras' }
    - { role: geerlingguy.nodejs, when: '"nodejs" in installed_extras' }
    - { role: drupalvm.www, tags: ['webserver'] }
    - { role: geerlingguy.drupal, tags: ['drupal'] }

    # Roles for security and stability on production.
    - { role: geerlingguy.security, when: extra_security_enabled }

  tasks:
    - import_tasks: tasks/sshd.yml
    - import_tasks: tasks/extras.yml
    - import_tasks: tasks/cron.yml
      tags: ['cron']

    - include_tasks: "{{ tasks_dir }}/install_code.yml"

    - include_tasks: tasks/dashboard.yml
      when: dashboard_install_dir is defined and dashboard_install_dir != ''
      tags: ['webserver', 'database', 'php']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks_dir|default(omit) }}"
