---
- name: install the code
  shell: composer install
  args:
    chdir: "{{ drupal_deploy_dir }}"
  become: no

- name: Make local drush executable globally
  file:
    src: "{{ drupal_deploy_dir }}/vendor/drush/drush/drush"
    dest: /usr/local/bin/drush
    state: link
    force: yes
