---
# Composer project settings.
drupal_build_composer_project: false
drupal_build_composer: false
drupal_composer_dependencies: []
composer_github_oauth_token: '931bca162b3d41aa92ba0bd63d0bb065f9865997'

# Drupal install settings.
drupal_site_name: "My Production Website"
drupal_core_path: "/var/www/drupal/web"
drupal_install_site: true
drupal_enable_modules: []

drupalvm_cron_jobs:
  - name: "Drupal Cron"
    minute: "*/15"
    job: "{{ drush_path }} -r {{ drupal_core_path }} core-cron --quiet"

# Other overrides.
php_version: "7.1"
php_sendmail_path: "/usr/sbin/sendmail -t -i"

installed_extras:
  - drush
  - varnish
  # - adminer
  # - pimpmylog

drush_launcher_version: "0.5.0"
drush_phar_url: https://github.com/drush-ops/drush-launcher/releases/download/{{ drush_launcher_version }}/drush.phar

# Add any extra Debian apt packages we would like installed.
extra_packages:
  - unzip
  - emacs24-nox
  - php-elisp
  - opendkim
  - opendkim-tools

# Other secure defaults.
dashboard_install_dir: ''
apache_packages_state: installed

# Restrict the firewall to only ports that are required for external services.
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
firewall_log_dropped_packets: true

# Set Apache to listen on port 81 (internal only), and Varnish on 80.
apache_listen_port: "81"
varnish_listen_port: "80"
varnish_default_backend_port: "81"
