---
# Ansible variables file for provisioning the Live Server
# Ansible variables common to Live and Dev sites are in config.yml
drupal_site_name: "BAPC Website"

# I think this next line is redundant TODO: see where it's (not) used (anymore)
drupal_site_install_extra_args: [ “--config-dir=/var/www/drupal/config/sync”]
# Other install args provided in prod.secrets.yml

# Set the domain for this site appropriately.
# vagrant_hostname: lookup('env','LIVESITE')
vagrant_hostname: "bradford-abbas.uk"
# Yes, the above variable does record the Live hostname
drupal_domain_regex: "{{ vagrant_hostname | regex_findall('([^.]+)')  | join('\\.') }}"

# mySQL security hardened on Live site
extra_security_enabled: true

# Apache VirtualHosts.
ssl_key_dest: "/etc/ssl/private/bradford-abbas.uk.key"
ssl_crt_dest: "/etc/ssl/certs/bradford-abbas.uk.crt"

apache_global_vhost_settings: |
  DirectoryIndex index.php index.html
  NameVirtualHost *:80

apache_vhost_redirect_parameters: |
  Redirect permanent / https://bradford-abbas.uk/

apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }} staging.{{ drupal_domain }}"
    extra_parameters: "{{ apache_vhost_redirect_parameters }}"

apache_vhosts_ssl:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }} staging.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: "{{ ssl_crt_dest }}"
    certificate_key_file: "{{ ssl_key_dest }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

ba_cron_day: "3"
ba_cron_hour: "05"
drupalvm_cron_jobs:
  - name: "Drupal Cron"
    minute: "*/45"
    job: "{{ drush_source_install_bin_path }} -r {{ drupal_core_path }} core-cron --quiet"

  - name: "Drupal Clear Views Cache"
    minute: "20"
    hour: "{{ ba_cron_hour }}"
    job: "{{ drush_source_install_bin_path }} cache:clear views   > /dev/null 2>&1"

  - name: "Drupal SQL dump"
    minute: "01"
    weekday: "{{ ba_cron_day }}"
    hour: "{{ ba_cron_hour }}"
    job: "{{ drush_source_install_bin_path }} -r {{ drupal_core_path }} sql:dump --extra-dump=--no-tablespaces --result-file=/tmp/bradford-abbas.uk.sql "

  - name: "Compress Drupal files"
    minute: "06"
    hour: "{{ ba_cron_hour }}"
    weekday: "{{ ba_cron_day }}"
    job: "/bin/tar -czf /tmp/BAPC_files.tar.gz  {{ drupal_core_path }}/sites/default/files "

  - name: "Backup Drupal SQL"
    minute: "11"
    hour: "{{ ba_cron_hour }}"
    weekday: "{{ ba_cron_day }}"
    job: "/usr/bin/s3cmd put  /tmp/bradford-abbas.uk.sql s3://bradford-abbas.uk.db "

  - name: "Backup Drupal Files"
    minute: "15"
    hour: "{{ ba_cron_hour }}"
    weekday: "{{ ba_cron_day }}"
    job: "/usr/bin/s3cmd put  /tmp/BAPC_files.tar.gz s3://bradford-abbas.uk.files-compressed "
