---
# Deploy from the project's Git repository.
drupal_deploy: false
drupal_deploy_repo: "https://github.com/iainhouston/bradford-abbas.uk.git"
drupal_deploy_dir: /var/www/drupal
#  User ansible-playbook's --extra-args for:
# drupal_deploy_version: refactorvm
drupal_composer_install_dir: /var/www/drupal
drupal_core_path: "{{ drupal_composer_install_dir }}/web"

drupal_install_site: false
drupal_site_name: "BAPC Staging Website"
drupal_site_install_extra_args: [ “--config-dir=/var/www/drupal/config/sync”]
# Other install args provided in prod.secrets.yml

# Set the domain for this site appropriately.
drupal_domain: "bradford-abbas.uk"
drupal_domain_regex: "{{ drupal_domain | regex_findall('([^.]+)')  | join('\\.') }}"
webserver_name: server
vagrant_hostname: "{{ webserver_name }}.{{ drupal_domain }}"

# setup DKIM; Place certs etc.
pre_provision_tasks_dir: "{{ config_dir }}/pre_provision_tasks/*"
post_provision_tasks_dir: "{{ config_dir }}/post_provision_tasks/*"

extra_security_enabled: true
installed_extras:
  - drush

drush_launcher_install: false
# Install Drush via Composer globally.
# Install from source (git clone + composer-based install).
drush_install_from_source: true
drush_source_install_bin_path: /usr/local/bin/drush
drush_source_install_path: /usr/local/share/drush
drush_source_install_version: "10.x"
drush_keep_updated: false
drush_force_update: false
drush_force_composer_install: false
drush_composer_cli_options: "--prefer-dist --no-interaction"
drush_clone_depth: 1

# Apache VirtualHosts.
# View the geerlingguy.apache Ansible Role README for more options.
apache_global_vhost_settings: |
  DirectoryIndex index.php index.html
  NameVirtualHost *:80

apache_vhost_redirect_parameters: |
  Redirect permanent / https://bradford-abbas.uk/

apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    extra_parameters: "{{ apache_vhost_redirect_parameters }}"

apache_vhosts_ssl:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }} staging.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: "/etc/ssl/certs/SSL.crt"
    certificate_key_file: "/etc/ssl/private/SSL.key"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

ba_cron_day: "3"
ba_cron_hour: "05"
drupalvm_cron_jobs:
  - name: "Drupal Cron"
    minute: "*/45"
    job: "{{ drush_source_install_bin_path }}/drush -r {{ drupal_core_path }} core-cron --quiet"

  - name: "Drupal Clear Views Cache"
    minute: "20"
    hour: "{{ ba_cron_hour }}"
    job: "{{ drush_source_install_bin_path }}/drush cache:clear views   > /dev/null 2>&1"

  - name: "Drupal SQL dump"
    minute: "01"
    weekday: "{{ ba_cron_day }}"
    hour: "{{ ba_cron_hour }}"
    job: "{{ drush_source_install_bin_path }}/drush -r {{ drupal_core_path }} sql:dump --result-file=/tmp/bradford-abbas.uk.sql "

  - name: "Compress Drupal files"
    minute: "06"
    hour: "{{ ba_cron_hour }}"
    weekday: "{{ ba_cron_day }}"
    job: "/bin/tar -czf /tmp/BAPC_files.tar.gz  {{ drupal_core_path }}/sites/default/files "

  - name: "Backup Drupal SQL"
    minute: "11"
    hour: "{{ ba_cron_hour }}"
    weekday: "{{ ba_cron_day }}"
    job: "/usr/bin/s3cmd put  /tmp/bradford-abbas.uk.sql s3://bradford-abbas.uk.db "

  - name: "Backup Drupal Files"
    minute: "15"
    hour: "{{ ba_cron_hour }}"
    weekday: "{{ ba_cron_day }}"
    job: "/usr/bin/s3cmd put  /tmp/BAPC_files.tar.gz s3://bradford-abbas.uk.files-compressed "
