---
# Deploy from the project's Git repository.
drupal_deploy: true
drupal_deploy_repo: "https://github.com/iainhouston/bradford-abbas.uk.git"
drupal_deploy_dir: /var/www/drupal

# Set the domain for this site appropriately.
drupal_domain: "staging.bradford-abbas.uk"
vagrant_hostname: "{{ drupal_domain }}"

nginx_hosts:
  - server_name: "{{ drupal_domain }} www.{{ drupal_domain }}"
    root: "{{ drupal_core_path }}"
    is_php: true

nginx_remove_default_vhost: true
nginx_ppa_use: true
nginx_vhost_template: "templates/nginx-vhost.conf.j2"
# path relative to current playbook.yml
post_provision_tasks_dir: "{{ config_dir }}/post_provision_tasks/*"

extra_packages:
  - unzip
  - emacs24-nox
  - php-elisp
  - opendkim
  - opendkim-tools
