---
# Deploy from the project's Git repository.
drupal_deploy: true
drupal_deploy_repo: "https://github.com/iainhouston/bradford-abbas.uk.git"
drupal_deploy_dir: /var/www/drupal

# Set the domain for this site appropriately.
drupal_domain: "bradford-abbas.uk"
# nginx vhost template needs punctuation escaped
drupal_domain_esc: "bradford-abbas\.uk"
vagrant_hostname: "{{ drupal_domain }}"


# setup DKIM; Place certs etc.
# path relative to current playbook.yml
pre_provision_tasks_dir: "{{ config_dir }}/pre_provision_tasks/*"
post_provision_tasks_dir: "{{ config_dir }}/post_provision_tasks/*"

extra_packages:
  - unzip
  - emacs24-nox
  - php-elisp
  - opendkim
  - opendkim-tools

nginx_remove_default_vhost: true
nginx_ppa_use: true
nginx_vhost_template: "{{ config_dir }}/templates/nginx-ssl-vhost.j2"
nginx_hosts:
  - server: "{{ drupal_domain }}"
    state: "present"
    filename: "{{ drupal_domain }}.conf"
