---
# Deploy from the project's Git repository.
drupal_deploy: true
drupal_deploy_repo: "https://github.com/iainhouston/bradford-abbas.uk.git"
drupal_deploy_dir: /var/www/drupal

# Set the domain for this site appropriately.
drupal_domain: "bradford-abbas.uk"
# nginx vhost template needs punctuation escaped
drupal_domain_esc: "bradford-abbas\\.uk"
vagrant_hostname: "{{ drupal_domain }}"


# setup DKIM; Place certs etc.
# path relative to current playbook.yml
pre_provision_tasks_dir: "{{ config_dir }}/pre_provision_tasks/*"
post_provision_tasks_dir: "{{ config_dir }}/post_provision_tasks/*"

extra_packages:
  - unzip
  - emacs24-nox
  - php-elisp
  - opendkim
  - opendkim-tools
  - s3cmd

nginx_remove_default_vhost: true
nginx_ppa_use: true
nginx_vhost_template: "{{ config_dir }}/templates/nginx-ssl-vhost.j2"
nginx_hosts:
  - server_name: "{{ drupal_domain }}"
    state: "present"
    filename: "{{ drupal_domain }}.conf"

ba_cron_hour: "05"
drupalvm_cron_jobs:
  - name: "Drupal Cron"
    minute: "*/15"
    job: "{{ drush_path }} -r {{ drupal_core_path }} core-cron --quiet"

  - name: "Drupal SQL dump"
    minute: "01"
    hour: "{{ ba_cron_hour }}"
    job: "{{ drush_path }} -r {{ drupal_core_path }} sql:dump --result-file=../bradford-abbas.uk.sql > /dev/null"

  - name: "Sync Drupal files"
    minute: "04"
    hour: "{{ ba_cron_hour }}"
    job: "/usr/bin/s3cmd sync  {{ drupal_core_path }}/sites/default/files/ s3://bradford-abbas.uk.files --exclude-from={{ drupal_core_path }}/../.s3ignore > /dev/null"

  - name: "Backup Drupal SQL"
    minute: "06"
    hour: "{{ ba_cron_hour }}"
    job: "/usr/bin/s3cmd put  /var/www/drupal/bradford-abbas.uk.sql s3://bradford-abbas.uk.db > /dev/null"
