---
# Deploy from the project's Git repository.
drupal_deploy: true
drupal_deploy_repo: "https://github.com/iainhouston/bradford-abbas.uk.git"
drupal_deploy_dir: /var/www/drupal

# Set the domain for this site appropriately.
drupal_domain: "bradford-abbas.uk"
vagrant_hostname: "{{ drupal_domain }}"

nginx_hosts:

nginx_remove_default_vhost: true
nginx_ppa_use: true
nginx_vhost_template: "templates/nginx-vhost.conf.j2"
# path relative to current playbook.yml
post_provision_tasks_dir: "{{ config_dir }}/post_provision_tasks/*"

extra_packages:
  - unzip
  - emacs24-nox
  - php-elisp
  - opendkim
  - opendkim-tools

nginx_vhosts:
  - listen: "443 ssl http2"
    server_name: "{{ drupal_domain }} www.{{ drupal_domain }}"
    root: "{{ drupal_core_path }}"
    is_php: true
    server_name_redirect: "{{ drupal_domain }}"
    index: "index.php index.html index.htm"
    state: "present"
    filename: "{{ drupal_domain }}.443.conf"
    extra_parameters: |
      location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass unix:/var/run/php5-fpm.sock;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
      }
      ssl_certificate     /etc/ssl/certs/SSL.crt;
      ssl_certificate_key /etc/ssl/private/SSL.key;
      ssl_protocols       TLSv1.1 TLSv1.2;
      ssl_ciphers         HIGH:!aNULL:!MD5;

  - listen: "80"
    server_name: "{{ drupal_domain }} www.{{ drupal_domain }}"
    return: "301 https://{{ drupal_domain }}$request_uri"
    filename: "{{ drupal_domain }}.80.conf"
    is_php: true

# During automation testing
  - listen: "80"
    server_name: "staging.{{ drupal_domain }}"
    filename: "staging.{{ drupal_domain }}.80.conf"
    is_php: true
