---
# Local Vagrant options.
vagrant_hostname: vagrant.bradford-abbas.uk
vagrant_machine_name: local-BAPC
vagrant_ip: 0.0.0.0

# Configure the synced folder.
vagrant_synced_folder_default_type: nfs
vagrant_synced_folders:
  - local_path: .
    destination: /var/www/drupal
    type: nfs

drupal_site_name: "My Development Website"
drupal_core_path: "/var/www/drupal/web"
drupal_install_site: true
# Undo some of the extra-hardened security settings in config.yml.
drupal_account_pass: admin
drupal_db_password: drupal
mysql_root_password: root

php_sendmail_path: "/opt/mailhog/mhsendmail"
installed_extras:
  - drush
  - mailhog
  - adminer
  - pimpmylog

extra_packages:
  - unzip
  - emacs24-nox
  - php-elisp

dashboard_install_dir: /var/www/dashboard
extra_security_enabled: false

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "443"
  - "8025"
firewall_log_dropped_packets: false

drupalvm_vagrant_version_min: '2.0.1'
drupalvm_ansible_version_min: '2.4'

nginx_hosts:
  - server_name: "{{ drupal_domain }} www.{{ drupal_domain }}"
    root: "{{ drupal_core_path }}"
    is_php: true

  - server_name: "adminer.{{ vagrant_hostname }}"
    root: "{{ adminer_install_dir }}"
    is_php: true

  - server_name: "xhprof.{{ vagrant_hostname }}"
    root: "{{ php_xhprof_html_dir }}"
    is_php: true

  - server_name: "pimpmylog.{{ vagrant_hostname }}"
    root: "{{ pimpmylog_install_dir }}"
    is_php: true

  - server_name: "{{ vagrant_ip }} dashboard.{{ vagrant_hostname }}"
    root: "{{ dashboard_install_dir }}"
    is_php: true
