---
# Local Vagrant options.
# ______________________
vagrant_box: geerlingguy/ubuntu1804
vagrant_hostname: vagrant.bradford-abbas.uk
vagrant_machine_name: local-BAPC
vagrant_user: vagrant
vagrant_ip: 0.0.0.0

# Configure the synced folder.
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: .
    destination: /var/www/drupalvm
    type: nfs
    create: true

vagrant_plugins:
  - name: vagrant-vbguest
  - name: vagrant-hostsupdater
  - name: vagrant-auto_network

# Minimum required versions.
drupalvm_vagrant_version_min: '2.2.6'
drupalvm_ansible_version_min: '2.9'

# Memory and CPU to use for this VM.
vagrant_memory: 2048
vagrant_cpus: 1
vagrant_public_ip: ""

# Local drupal site specs
# _______________________
# Dont allow Drupal VM to be accessed via a public network interface

# Composer-project installs a basic site for us on the Dev VM
drupal_install_site: false

drupal_site_name: "BAPC Development Website"
drush_path: /usr/local/bin/drush

php_date_timezone: "Europe/London"
php_sendmail_path: "/opt/mailhog/mhsendmail"
installed_extras:
  # - drush
  - mailhog
  - adminer
  - pimpmylog
  - xdebug

php_xdebug_default_enable: 1
php_xdebug_coverage_enable: 0
php_xdebug_version: "2.8.1"
php_xdebug_cli_disable: yes
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
php_xdebug_max_nesting_level: 256
php_xdebug_remote_host: "{{ ansible_default_ipv4.gateway }}"
php_xdebug_idekey: PHPSTORM

dashboard_install_dir: /var/www/dashboard
extra_security_enabled: false

firewall_enabled: true
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "443"
  - "8025"
firewall_log_dropped_packets: false
firewall_disable_firewalld: true
firewall_disable_ufw: true

# Apache VirtualHosts.
# View the geerlingguy.apache Ansible Role README for more options.
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

# For production we use Ansible Vault-encrypted prod_secrets.yml
drupal_account_pass: admin
drupal_db_user: drupal
drupal_db_name: drupal
drupal_db_password: drupal
mysql_root_password: root

adminer_install_filename: index.php

pimpmylog_install_dir: /usr/share/php/pimpmylog
pimpmylog_grant_all_privs: true

pre_provision_tasks_dir: "{{ config_dir }}/pre_provision_tasks/*"
post_provision_tasks_dir: "{{ config_dir }}/post_provision_tasks/*"
