---
# Ansible variables file for provisioning the Development Server
# Ansible variables common to Live and Dev sites are in config.yml

#
# Virtual Mchine options.
# ______________________

# See vagrant_plugins below that specifies "vagrant plugin install vagrant-parallels"
# bento boxes know somehow that they are for Parallels virtual machines
# and not Oracle Virtualbox machines
vagrant_box: "bento/ubuntu-22.04"
vagrant_box_version: "202502.21.0"

# DEVSITE is defined in `SYMBOLS.sh` and is
# most likely something like `vagrant.bradford-abbas.uk`

# Unfortunately, the following does not work, so we hard-coded vagrant_hostname
#vagrant_hostname: "{{ lookup('env', 'DEVSITE') }}"

# Even though the following DOES work as expected:
# ansible all -i localhost, -m debug -a msg="{{ lookup('env', 'DEVSITE') }}"

vagrant_hostname: bradford-abbas.uk
vagrant_machine_name: BAPC-Dev

vagrant_user: vagrant


# or vagrant_ip: 0.0.0.0 then plugin vagrant-auto_network will find a spare IP Address automatically
vagrant_ip: 10.20.1.2
vagrant_synced_folder_default_type: nfs
vagrant_gui: false

# Configure the synced folder.
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: .
    destination: "{{ drupal_deploy_dir }}"
    type: nfs
    create: true

# these values set by vagrant (see Vagrantfile.local
# used by nfsd in /etc/exports
guest_files_owner: vagrant
guest_files_group: www-data

vagrant_plugins:
  - name: vagrant-vbguest
  - name: vagrant-hostsupdater
  - name: vagrant-parallels
  - name: vagrant-auto_network
  - name: vagrant-bindfs

# Minimum required versions.
drupalvm_vagrant_version_min: '2.2.18'
drupalvm_ansible_version_min: '2.10'

vagrant_memory: 2048
vagrant_cpus: 1
vagrant_public_ip: ""

# Dev system requires port 8025 for Mailhog
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "443"
  - "8025"

drupal_site_name: "BAPC Development Website"

# installed_extras are web / server utilities (and not Ubuntu / Linux ones)
installed_extras:
  - drush
  - adminer
  - xdebug
  - mailhog
  - upload-progress

# See role ../library/provisioning/roles/iainhouston.php-xdebug for default XDEBUG php.ini values
php_xdebug_mode: debug
php_start_with_request: trigger
php_xdebug_trigger_value: PHPSTORM
php_xdebug_discover_client_host: true
php_xdebug_client_port: 9003

dashboard_install_dir: /var/www/dashboard

# Apache VirtualHosts.
# View the geerlingguy.apache Ansible Role README for more options.
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

# For production we use Ansible Vault-encrypted `secrets.yml`
drupal_account_name: admin
drupal_account_pass: admin
drupal_db_user: drupal
drupal_db_name: drupal
drupal_db_password: drupalVagrant
mysql_root_password: root

adminer_install_filename: index.php

drupalvm_cron_jobs:
  - name: "Drupal Cron"
    minute: "*/45"
    job: "{{ drush_source_install_bin_path }} -r {{ drupal_core_path }} core-cron --quiet  --uri=http://{{ drupal_domain }}"


