---
# Local Vagrant options.
vagrant_hostname: vagrant.bradford-abbas.uk
vagrant_machine_name: local-BAPC
vagrant_ip: 0.0.0.0

# Configure the synced folder.
vagrant_synced_folder_default_type: nfs
vagrant_synced_folders:
  - local_path: .
    destination: /var/www/drupal
    type: nfs

drupal_site_name: "My Development Website"
drupal_core_path: "/var/www/drupal/web"
drupal_install_site: true
# Undo some of the extra-hardened security settings in config.yml.
drupal_account_pass: admin
drupal_db_password: drupal
mysql_root_password: root

php_sendmail_path: "/opt/mailhog/mhsendmail"
installed_extras:
  - drush
  - mailhog
  - varnish
  - adminer
  - pimpmylog

extra_packages:
  - unzip
  - emacs24-nox
  - php-elisp

dashboard_install_dir: /var/www/dashboard
extra_security_enabled: false

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "8025"
firewall_log_dropped_packets: false

# Set Apache to listen on port 80, and Varnish on 81.
apache_listen_port: "80"
varnish_listen_port: "81"
varnish_default_backend_port: "80"


drupalvm_vagrant_version_min: '1.8.6'
drupalvm_ansible_version_min: '2.2'
