---
- name: Template Drupal settings file to sites/default/
  template:
    src: "{{ config_dir }}/saved_default_settings/settings.php.j2"
    dest: "{{ drupal_core_path }}/sites/default/settings.php"
    mode: u=r,g=r,o-rwx

- name: Ensure settings are protected is writable by http server
  file:
    path: "{{ drupal_core_path }}/sites/default/settings.php"
    state: file
    owner: "{{drupalvm_webserver_user}}"
    group: "{{drupalvm_webserver_user}}"
    mode: u=r,g=r,o-rwx
  become: yes
  tags: ['drupal', 'prod_only']

- name: Configure Dev Settings
  blockinfile:
    dest: "{{ drupal_core_path }}/sites/default/settings.php"
    block: |
      if (file_exists($app_root . '/' . $site_path . '/settings.local.php')) {
        include $app_root . '/' . $site_path . '/settings.local.php';
      }
  tags: ['test_only']

- name: Copy services file to sites/default/
  copy:
    src: "{{ config_dir }}/saved_default_settings/services.yml"
    dest: "{{ drupal_core_path }}/sites/default/services.yml"
    mode: u=r,g=r,o-rw
    
- name: Copy Development services file to sites/
  copy:
    src: "{{ config_dir }}/saved_default_settings/development.services.yml"
    dest: "{{ drupal_core_path }}/sites/development.services.yml"
    mode: u=rw,g=rw,o-rw
  tags: ['test_only']

- name: Copy settings.local file to sites/default/
  copy:
    src: "{{ config_dir }}/saved_default_settings/settings.local.php"
    dest: "{{ drupal_core_path }}/sites/default/settings.local.yml"
    mode: u=r,g=r,o-rw

