---
- name: Ensure required DKIM packages are installed (OpenDKIM)
  apt: name=opendkim state=present

- name: Ensure required DKIM packages are installed (OpenDKIM tools)
  apt: name=opendkim-tools state=present

- name: Place DKIM key file
  copy:
    src: "{{ config_dir }}/certs/dkim.key"
    dest: /etc/postfix/dkim.key
    mode: a=r,go-rw
    owner: root
  become: yes

- name: Configure OpenDKIM - Comment out any pre-installed Socket spec
  replace:
    path: /etc/opendkim.conf
    before: 'BEGIN ANSIBLE MANAGED BLOCK'
    regexp: '^Socket'
    replace: '# Socket'

- name: Configure OpenDKIM - specify BA specifics
  blockinfile:
    dest: /etc/opendkim.conf
    block: |
      Domain                  {{ drupal_domain }}
      KeyFile                 /etc/postfix/dkim.key
      Selector                mail
      Socket                  inet:8891@127.0.0.1
      SyslogSuccess           yes

- name: Configure Postfix MTA
  blockinfile:
    dest: /etc/postfix/main.cf
    block: |
      # Per https://help.ubuntu.com/community/Postfix/DKIM
      # Enable DKIM signing.
      milter_default_action = accept
      milter_protocol = 2
      smtpd_milters = inet:127.0.0.1:8891
      non_smtpd_milters = inet:127.0.0.1:8891
      # please see https://anandarajpandey.com/2019/12/30/postfix-how-to-prevent-open-relay/
      smtpd_sender_restrictions = permit_sasl_authenticated reject_unknown_sender_domain
      # for info on postfix queues please see http://www.postfix.org/QSHAPE_README.html
      smtpd_recipient_restrictions = reject_non_fqdn_recipient  reject_unlisted_reciepient  permit_sasl_authenticated reject_invalid_hostname

- name: Ensure unauthorized relay attempts are rejected
  ansible.builtin.lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^smtpd_relay_restrictions'
    line: smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated reject_unauth_destination

# I suspect this is redundant in Ubuntu 18.04
# as "Socket inet:8891@127.0.0.1" is "required" in  /etc/opendkim.conf
- name: Place file specifying DKIM Sockets
  copy:
    content: 'SOCKET="inet:8891@127.0.0.1" '
    dest: /etc/default/opendkim


- name: restart OpenDKIM
  service: name=opendkim state=restarted

- name: restart Postfix
  service: name=postfix state=restarted
