---
- name: Copy xdebug ini into main extension config folder.
  template:
    src: xdebug.ini.j2
    dest: "{{ item }}/20-xdebug.ini"
    owner: root
    group: root
    mode: 0644
  when: "'cli' not in item or ('cli' in item and not php_xdebug_cli_disable)"
  with_items: "{{ php_extension_conf_paths }}"
  notify:
    - restart webserver
    - restart php-fpm
