---
- hosts: drupal_live
  gather_facts: no

  vars_files:
    - secrets.yml

  tasks:
    - name: Create admin user account.
      user:
        name: "{{ admin_user }}"
        create_home: yes
        home: "/home/{{ admin_user }}"
        generate_ssh_key: yes
        ssh_key_comment: "ansible-{{ inventory_hostname }}"
        password: "{{ admin_password }}"
        groups: "{{ admin_group }},www-data"
        shell: /bin/bash
      become: yes

    - name: Add local SSH public key to admin account authorized_keys.
      authorized_key:
        user: "{{ admin_user }}"
        key: "{{ lookup('file', admin_pubkey) }}"
        manage_dir: yes
      when: admin_copy_ssh_pubkey
      become: yes

    - name: Disable requiretty.
      lineinfile:
        dest: /etc/sudoers
        regexp: '^Defaults.+requiretty'
        line: 'Defaults    !requiretty'
        state: present
      become: yes
