---
# Ansible variables file for provisioning the Live Server
# Ansible variables common to Live and Dev sites are in config.yml
drupal_site_name: "BAPC Website"

# I think this next line is redundant TODO: see where it's (not) used (anymore)
drupal_site_install_extra_args: [ “--config-dir=/var/www/drupal/config/sync”]
# Other install args provided in prod.secrets.yml

# Set the domain for this site appropriately.
# vagrant_hostname: lookup('env','LIVESITE')
vagrant_hostname: "bradford-abbas.uk"
# Yes, the above variable does record the Live hostname
drupal_domain_regex: "{{ vagrant_hostname | regex_findall('([^.]+)')  | join('\\.') }}"

# mySQL security hardened on Live site
extra_security_enabled: true

guest_files_owner:  "{{ drupalvm_user }}"
guest_files_group: "{{ drupalvm_user }}"

# Apache VirtualHosts.
ssl_key_dest: "/etc/ssl/private/bradford-abbas.uk.key"
ssl_crt_dest: "/etc/ssl/certs/bradford-abbas.uk.crt"

apache_global_vhost_settings: |
  DirectoryIndex index.php index.html
  NameVirtualHost *:80

apache_vhost_redirect_parameters: "Redirect permanent / https://{{ drupal_domain }}/"

apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }} "
    extra_parameters: "{{ apache_vhost_redirect_parameters }}"

apache_vhosts_ssl:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: "{{ ssl_crt_dest }}"
    certificate_key_file: "{{ ssl_key_dest }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

ba_cron_day: "3"
ba_cron_hour: "05"

# Every so often (Wednesdays) thr DB and all public and private files are backed up to AWS S3 buckets
backup_script_path: /usr/local/sbin/backup2S3

# `mailcount` lets us know if there is an excessive number of emails on the mail queue
mailcount_ceiling: 10
mailcount_recipient: iainhouston@me.com
mailcount_script_path: /usr/local/sbin/mailcount

drupalvm_cron_jobs:
  - name: "Drupal Cron"
    minute: "*/45"
    job: "{{ drush_source_install_bin_path }} -r {{ drupal_core_path }} core-cron --quiet  --uri=https://{{ drupal_domain }}"

  - name: "Drupal Clear Views Cache"
    minute: "20"
    hour: "{{ ba_cron_hour }}"
    job: "{{ drush_source_install_bin_path }} cache:clear views > /dev/null 2>&1"

  - name: "Monitor postfix mail queue"
    minute: "25"
    hour: "{{ ba_cron_hour }}"
    job: "{{ mailcount_script_path }} > /dev/null 2>&1"

  - name: "Drupal SQL dump and BAPC Static Files dump"
    minute: "01"
    weekday: "{{ ba_cron_day }}"
    hour: "{{ ba_cron_hour }}"
    job: "{{ backup_script_path }} > /dev/null 2>&1"
