---
-   hosts: all
    become: no

    vars_files:

        -   ../vm/config.yml
        -   provision.config.yml

    tasks:

        -   name: Put website into maintenance mode
            shell:
              cmd: |
                  drush state:set system.maintenance_mode 1 --input-format=integer
                  drush cache:rebuild
              chdir: "{{ drupal_core_path }}"

        -   name: copy SSL certificate
            copy:
              src: "{{ project_dir }}/vm/certs/SSL.crt"
              dest: "{{ ssl_crt_dest }}"
              owner: root
              group: root
              mode: a-w,o-r,ug+r
            become: yes

        -   name: copy SSL key
            copy:
              src: "{{ project_dir }}/vm/certs/SSL.key"
              dest: "{{ ssl_key_dest }}"
              owner: root
              group: ssl-cert
              mode: a-w,o-r,ug+r
            become: yes

        -   name: Restart web server
            shell:
                cmd: |
                    "systemctl restart php{{ php_version }}-fpm"
                    systemctl restart apache2.service
            become: yes
       
        # When git was initialised originally: git config core.sparseCheckout true
        # With --depth=1, Git downloads only the latest commit and avoids fetching older history.
        - name: Pull only the files originally specified in .git/info/sparse-checkout
          command: git pull --depth=1 origin master
          args:
            chdir: "{{ drupal_deploy_dir }}"

        -   name: install the latest code
            composer:
                command: install
                working_dir: "{{ drupal_deploy_dir }}"

        -   name: Rebuild Drupal into PHP cache
            shell:
              cmd: drush cache:rebuild
              chdir: "{{ drupal_core_path }}"

        -   name: Update Drupal database
            shell:
              cmd: drush updatedb -y
              chdir: "{{ drupal_core_path }}"

        -   name: Import latest configuration
            shell:
              cmd: drush config:import -y
              chdir: "{{ drupal_core_path }}"

        -   name: Get website out of maintenance mode
            shell:
                cmd: |
                    drush cache:rebuild
                    drush state:set system.maintenance_mode 0 --input-format=integer
                chdir: "{{ drupal_core_path }}"
