echo "checkVersions  - Review  software required for development"
echo "cloneLive2Dev  - Sync Live database and static files to Dev server"
echo "reloadDevDB    - Reload Dev database with most recently downloaded live database"
echo "endev          - Enable development modules in Dev site"
echo "safecex        - Safe export of Dev site's configuration"
echo "updateLiveCode - Code and Config to Live site"
echo "livemaint      - Put Live system into maintenance mode"
echo "liveumaint     - Take Live system out of maintenance mode"
echo "_________________________________________________________________________________"
echo "There are other utilty scripts aliased in ${GREEN}SYMBOLS.sh${NC}"
echo " "
echo "${GREEN}drush alias ${RED}${LIVEALIAS}${GREEN} for the Live Server at ${RED}https://${LIVESITE}${NC}"
echo "${GREEN}drush alias ${RED}${STAGEALIAS}${GREEN} for the Staging Server at ${RED}https://${STAGESITE}${NC}"
echo "${GREEN}drush alias ${RED}${DEVALIAS}${GREEN} for the Development Server at ${RED}http://${DEVSITE}${NC}"
