---
# Install and configure MailHog.
- name: Ensure mailhog install directory exists.
  file:
    path: "{{ mailhog_install_dir }}"
    owner: root
    group: root
    state: directory
    mode: 0755

- name: Ensure Go language is installed
  apt:
    name: golang-go
    state: present

- name: compile the Mailhog code
  ansible.builtin.shell: go get  github.com/mailhog/MailHog

- name: move the Mailhog code to its install directory
  shell:  cp -f /root/go/bin/MailHog "{{ mailhog_install_dir }}/mailhog"

- name: Copy mailhog systemd unit file into place (for systemd systems like Ubuntu).
  template:
    src: mailhog.unit.j2
    dest: /etc/systemd/system/mailhog.service
    owner: root
    group: root
    mode: 0755

- name: Ensure mailhog is enabled and will start on boot.
  service: name=mailhog state=started enabled=yes
